# Generated by Django 4.1.5 on 2023-01-09 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_image', models.URLField(verbose_name='S3 image URL.')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created date.')),
                ('geolocation', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo geolocation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Photo description.')),
                ('mentions', models.ManyToManyField(max_length=512, to=settings.AUTH_USER_MODEL, verbose_name='Mentioned people in the photo..')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Created by.')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
